name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MUSL build target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build without dylib
      run: cargo build --target x86_64-unknown-linux-musl --release
    - name: Run tests
      run: cargo test --verbose
