name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install MUSL build target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build without dylib
      run: cargo build --target x86_64-unknown-linux-musl --release
    - name: Docker build
      run: |
        mkdir -p ./result
        mkdir -p ./output
        mkdir -p ./case

        echo "1 2" >> ./case/1.in
        echo "3 5" >> ./case/2.in
    - name: Build sample programs
      run: |
        g++ ./test/ac.cpp -O2 -std=c++17 -o ./test/ac.o
        g++ ./test/re.cpp -O2 -std=c++17 -o ./test/re.o
        g++ ./test/wa.cpp -O2 -std=c++17 -o ./test/wa.o
        g++ ./test/tle.cpp -O2 -std=c++17 -o ./test/tle.o
        g++ ./test/mle.cpp -O2 -std=c++17 -o ./test/mle.o
    - name: Run tests
      run: cargo test --verbose
